### ISSUE TITLE
ActivitiesController.Get(int) should have return type ActionResult<Activity>

### ISSUE THREAD

**Issue by jhannes** [kasuken/fakerestapi#4]
The Get() method returns a single Activity, but the signature specifies List<Activity>

https://github.com/kasuken/fakerestapi/blob/3da2fc66d9efed380ac5e80e51bb0503de23f91d/src/FakeRESTApi.Web/Controllers/ActivitiesController.cs#L41

As evidenced from https://fakerestapi.azurewebsites.net/api/v1/Activities/1

**Comment by kasuken** [comment]
Fixed it.
Thanks.
